[
  {
    "id": 1,
    "placa": "GH7799D",
    "nombre": "GH7799D",
    "tipo": "Camioneta",
    "marca": "PEUGEOUT",
    "modelo": "PARTNER",
    "año": 2024,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "Gasolina"
  },
  {
    "id": 2,
    "placa": "GE8099D",
    "nombre": "GE8099D",
    "tipo": "Camioneta",
    "marca": "CHEVROLET",
    "modelo": "TORNADO VAN",
    "año": 2024,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "Gasolina"
  },
  {
    "id": 3,
    "placa": "GU8362C",
    "nombre": "GU8362C",
    "tipo": "Camioneta",
    "marca": "VOLKSWAGEN",
    "modelo": "SAVEIRO",
    "año": 2022,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "Gasolina"
  },
  {
    "id": 4,
    "placa": "GE8098D",
    "nombre": "GE8098D",
    "tipo": "Camioneta",
    "marca": "CHEVROLET",
    "modelo": "TORNADO VAN",
    "año": 2024,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "Gasolina"
  },
  {
    "id": 5,
    "placa": "GN4214C",
    "nombre": "GN4214C",
    "tipo": "Camioneta",
    "marca": "VOLKSWAGEN",
    "modelo": "TRANSPORTER",
    "año": 2021,
    "estado": "Inactivo",
    "departamento": "Distribuciones",
    "combustible": "Diesel"
  },
  {
    "id": 6,
    "placa": "78L993",
    "nombre": "78L993",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2025,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "ELECTRICO"
  },
  {
    "id": 7,
    "placa": "80L936",
    "nombre": "80L936",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "Distribuciones",
    "combustible": "ELECTRICO"
  },
  {
    "id": 8,
    "placa": "GMK351C",
    "nombre": "GMK351C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2012,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 9,
    "placa": "GPH909C",
    "nombre": "GPH909C",
    "tipo": "Automovil",
    "marca": "VOLKSWAGEN",
    "modelo": "JETTA",
    "año": 2017,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 10,
    "placa": "56EDX3",
    "nombre": "56EDX3",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 11,
    "placa": "54DZE4",
    "nombre": "54DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2017,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 12,
    "placa": "GJT068F",
    "nombre": "GJT068F",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 13,
    "placa": "GPY629F",
    "nombre": "GPY629F",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 14,
    "placa": "GJT069F",
    "nombre": "GJT069F",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 15,
    "placa": "GLX098F",
    "nombre": "GLX098F",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 16,
    "placa": "GGY468G",
    "nombre": "GGY468G",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 17,
    "placa": "GB6788C",
    "nombre": "GB6788C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 18,
    "placa": "GB6641B",
    "nombre": "GB6641B",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 19,
    "placa": "22EDX3",
    "nombre": "22EDX3",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 20,
    "placa": "38DZE4",
    "nombre": "38DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 21,
    "placa": "GMK357C",
    "nombre": "GMK357C",
    "tipo": "Automovil",
    "marca": "HONDA",
    "modelo": "CIVIC",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 22,
    "placa": "GMJ900C",
    "nombre": "GMJ900C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 23,
    "placa": "39DZE4",
    "nombre": "39DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 24,
    "placa": "57DZE4",
    "nombre": "57DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 25,
    "placa": "36DZE4",
    "nombre": "36DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2016,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 26,
    "placa": "53MLM2",
    "nombre": "53MLM2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 27,
    "placa": "GB6787C",
    "nombre": "GB6787C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 28,
    "placa": "65DZE1",
    "nombre": "65DZE1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2016,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 29,
    "placa": "68DZE1",
    "nombre": "68DZE1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 30,
    "placa": "H8J46Y",
    "nombre": "H8J46Y",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 31,
    "placa": "22DZE2",
    "nombre": "22DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 32,
    "placa": "15DZE2",
    "nombre": "15DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 33,
    "placa": "54EDX3",
    "nombre": "54EDX3",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 34,
    "placa": "52EJG4",
    "nombre": "52EJG4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 35,
    "placa": "12DZE2",
    "nombre": "12DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 36,
    "placa": "18DZE2",
    "nombre": "18DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 37,
    "placa": "97DZE1",
    "nombre": "97DZE1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2017,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 38,
    "placa": "GNL742F",
    "nombre": "GNL742F",
    "tipo": "Automovil",
    "marca": "CHEVROLET",
    "modelo": "AVEO",
    "año": 2024,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 39,
    "placa": "06DZE2",
    "nombre": "06DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2016,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 40,
    "placa": "H5L22C",
    "nombre": "H5L22C",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 41,
    "placa": "34EDX3",
    "nombre": "34EDX3",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 42,
    "placa": "H3C63R",
    "nombre": "H3C63R",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2025,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 43,
    "placa": "48EDX3",
    "nombre": "48EDX3",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 44,
    "placa": "GE4288C",
    "nombre": "GE4288C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 45,
    "placa": "GA3497C",
    "nombre": "GA3497C",
    "tipo": "Camioneta",
    "marca": "NISSAN",
    "modelo": "NP300",
    "año": 2014,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 46,
    "placa": "GR3706D",
    "nombre": "GR3706D",
    "tipo": "Camioneta",
    "marca": "NISSAN",
    "modelo": "NP300",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 47,
    "placa": "GR3707D",
    "nombre": "GR3707D",
    "tipo": "Camioneta",
    "marca": "NISSAN",
    "modelo": "NP300",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 48,
    "placa": "GB6663B",
    "nombre": "GB6663B",
    "tipo": "Camioneta",
    "marca": "VOLKSWAGEN",
    "modelo": "TRANSPORTER",
    "año": 2018,
    "estado": "Inactivo",
    "departamento": "EMA",
    "combustible": "Diesel"
  },
  {
    "id": 49,
    "placa": "GNL743F",
    "nombre": "GNL743F",
    "tipo": "Automovil",
    "marca": "CHEVROLET",
    "modelo": "AVEO",
    "año": 2024,
    "estado": "Inactivo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 50,
    "placa": "GWK204F",
    "nombre": "GWK204F",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "MARCH",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 51,
    "placa": "GNL744F",
    "nombre": "GNL744F",
    "tipo": "Automovil",
    "marca": "CHEVROLET",
    "modelo": "AVEO",
    "año": 2024,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 52,
    "placa": "GMK359C",
    "nombre": "GMK359C",
    "tipo": "Camioneta",
    "marca": "HONDA",
    "modelo": "CRV",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 53,
    "placa": "GRF222C",
    "nombre": "GRF222C",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "TSURU",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 54,
    "placa": "GLJ810E",
    "nombre": "GLJ810E",
    "tipo": "Automovil",
    "marca": "NISSAN",
    "modelo": "TSURU",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 55,
    "placa": "48EDZ8",
    "nombre": "48EDZ8",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2013,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 56,
    "placa": "52EDZ8",
    "nombre": "52EDZ8",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 57,
    "placa": "52DZE4",
    "nombre": "52DZE4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 58,
    "placa": "19DZE2",
    "nombre": "19DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 59,
    "placa": "11DZE2",
    "nombre": "11DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 60,
    "placa": "H1E84M",
    "nombre": "H1E84M",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 61,
    "placa": "02DZE2",
    "nombre": "02DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 62,
    "placa": "03DZE2",
    "nombre": "03DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 63,
    "placa": "16DZE2",
    "nombre": "16DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 64,
    "placa": "H3C60R",
    "nombre": "H3C60R",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2025,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 65,
    "placa": "94MDU9",
    "nombre": "94MDU9",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 66,
    "placa": "94DZE1",
    "nombre": "94DZE1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2019,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 67,
    "placa": "64MBU4",
    "nombre": "64MBU4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 68,
    "placa": "92DZE1",
    "nombre": "92DZE1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 69,
    "placa": "H3C62R",
    "nombre": "H3C62R",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2025,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 70,
    "placa": "H3C61R",
    "nombre": "H3C61R",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2025,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 71,
    "placa": "88MBE7",
    "nombre": "88MBE7",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2018,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 72,
    "placa": "43EML4",
    "nombre": "43EML4",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 73,
    "placa": "24DZE2",
    "nombre": "24DZE2",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2020,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 74,
    "placa": "27MEU1",
    "nombre": "27MEU1",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2015,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 75,
    "placa": "H4L30J",
    "nombre": "H4L30J",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 76,
    "placa": "H4L28J",
    "nombre": "H4L28J",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 77,
    "placa": "H4L29J",
    "nombre": "H4L29J",
    "tipo": "Motocicleta",
    "marca": "HONDA",
    "modelo": "CARGO 150",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Gasolina"
  },
  {
    "id": 78,
    "placa": "80L928",
    "nombre": "80L928",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 79,
    "placa": "79L545",
    "nombre": "79L545",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2025,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 80,
    "placa": "88L382",
    "nombre": "88L382",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 81,
    "placa": "88L381",
    "nombre": "88L381",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 82,
    "placa": "88L383",
    "nombre": "88L383",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 83,
    "placa": "88L384",
    "nombre": "88L384",
    "tipo": "Automovil",
    "marca": "BYD",
    "modelo": "DOLPHIN",
    "año": 2026,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  },
  {
    "id": 84,
    "placa": "73L716",
    "nombre": "73L716",
    "tipo": "Automovil",
    "marca": "JINPENG",
    "modelo": "LINGBOX",
    "año": 2023,
    "estado": "Activo",
    "departamento": "EMA",
    "combustible": "Electrico"
  }
]